# Generated by Django 5.1.5 on 2025-07-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=75)),
                ('login', models.CharField(max_length=20)),
                ('pass_field', models.CharField(db_column='pass', max_length=32)),
                ('destination', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('auteur', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'auteur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nomrc', models.CharField(max_length=100)),
                ('n_enregistrement', models.SmallIntegerField()),
                ('datsaisi_c', models.DateField()),
            ],
            options={
                'db_table': 'collecte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collecteur',
            fields=[
                ('nomrc', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'collecteur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nomc', models.CharField(max_length=100)),
                ('dat_ctrl', models.DateField()),
                ('observation', models.CharField(blank=True, max_length=200, null=True)),
                ('retourne', models.CharField(max_length=3)),
                ('dat_retour', models.DateField(blank=True, null=True)),
                ('dat_valid', models.DateField()),
                ('visa', models.CharField(max_length=50)),
                ('n_enregistrement', models.SmallIntegerField()),
                ('dat_recepc', models.DateField()),
            ],
            options={
                'db_table': 'control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Controleur',
            fields=[
                ('nomc', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'controleur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Controleurpv',
            fields=[
                ('controleur', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'controleurpv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('type', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'depot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('n_enregistrement', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('titre_article', models.CharField(blank=True, max_length=200, null=True)),
                ('pages', models.CharField(blank=True, max_length=30, null=True)),
                ('domaine', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=100)),
                ('periodicite', models.CharField(default='0', max_length=3)),
                ('vol', models.CharField(max_length=25)),
                ('tom', models.CharField(max_length=25)),
                ('num', models.CharField(max_length=25)),
                ('statut', models.CharField(default='0', max_length=10)),
                ('n_periodique', models.SmallIntegerField(blank=True, null=True)),
                ('lang', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('domaine', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'domaine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('auteur', models.CharField(max_length=255)),
                ('n_enregistrement', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'ecriture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('editeur', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'editeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('editeur', models.CharField(max_length=255)),
                ('n_enregistrement', models.SmallIntegerField()),
                ('date_edition', models.DateField()),
                ('ville_edition', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'edition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fournit',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('n_enregistrement', models.SmallIntegerField()),
                ('date_reception', models.DateField()),
                ('obligation', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fournit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indexation',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=100)),
                ('n_enregistrement', models.SmallIntegerField()),
                ('dat_reception', models.DateField()),
                ('dat_indexation', models.DateField()),
                ('dat_saisi', models.DateField()),
                ('dat_envoi', models.DateField()),
            ],
            options={
                'db_table': 'indexation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indexeur',
            fields=[
                ('nomi', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'indexeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suiveur',
            fields=[
                ('noms', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'suiveur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=100)),
                ('n_enregistrement', models.SmallIntegerField()),
                ('datenvoi_t', models.DateField()),
                ('dat_rsuivi', models.DateField()),
                ('datsaisi_ic', models.DateField()),
                ('datenvoi_sir', models.DateField()),
                ('dat_pv', models.DateField()),
                ('dat_mont', models.DateField()),
                ('dat_rrsuivi', models.DateField()),
                ('datsaisi_pv', models.DateField()),
            ],
            options={
                'db_table': 'suivi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vue',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('controleur', models.CharField(max_length=100)),
                ('n_enregistrement', models.SmallIntegerField()),
                ('dat_ctrl', models.DateField()),
                ('visa', models.CharField(max_length=50)),
                ('dat_recepv', models.DateField()),
            ],
            options={
                'db_table': 'vue',
                'managed': False,
            },
        ),
    ]
